# Generated by Django 4.0.4 on 2022-07-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_competencia_escola_interesse_lingua_pessoa_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/skill_images'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='portfolio/images/project_images'),
        ),
    ]
