# Generated by Django 4.0.4 on 2022-07-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_competencia_image_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='image',
            field=models.ImageField(blank=True, upload_to='skill_images'),
        ),
    ]
