# Generated by Django 4.0.4 on 2022-07-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_competencia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio/static/portfolio/images/skill_images'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='portfolio/static/portfolio/images/project_images'),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='portfolio/static/portfolio/images/TFC_images'),
        ),
    ]
