# Generated by Django 4.0.4 on 2023-06-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_competencia_image_alter_projeto_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='link_github',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
