# Generated by Django 4.0.4 on 2023-06-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_tfc_linkgithub_alter_tfc_linkyoutube_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='link_github',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
